# Ubicaci贸n: /Backend/docker-compose.yml

version: '3.8'

# Ubicaci贸n: /TurnyChain/docker-compose.yml

# 1. Definimos nuestra red personalizada al principio
networks:
  turny_chain_network:
    driver: bridge

services:
  # Servicio para la base de datos PostgreSQL
  postgres:
    build: ./Backend/baseDatos
    container_name: restaurant_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 2. Asignamos el servicio a nuestra red
    networks:
      - turny_chain_network
    restart: unless-stopped

  # Servicio para la aplicaci贸n de Go (backend)
  app:
    build: ./Backend/api
    container_name: restaurant_app_container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "user=postgres password=1234 dbname=restaurant_db host=postgres sslmode=disable"
    # 3. Asignamos el servicio a nuestra red
    networks:
      - turny_chain_network
    restart: unless-stopped

  # Servicio para la aplicaci贸n de React (frontend)
  frontend:
    build: ./Frontend/core
    container_name: restaurant_ui_container
    ports:
      - "5173:80"
    depends_on:
      - app
    # 4. Asignamos el servicio a nuestra red
    networks:
      - turny_chain_network
    restart: unless-stopped

# 5. Declaramos el volumen como antes
volumes:
  postgres_data:

