version: '3.8'

services:
  # --- 1. BASE DE DATOS ---
  postgres:
    build: ./Backend/baseDatos
    container_name: restaurant_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # --- 2. BACKEND (API GO) ---
  backend:
    build: ./Backend/api
    container_name: restaurant_app_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    
    # [IMPORTANTE] Esto permite que el contenedor vea tu Anvil corriendo en la terminal
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      # DB
      DATABASE_URL: "user=postgres password=1234 dbname=restaurant_db host=postgres sslmode=disable"
      
      # BLOCKCHAIN (Asegúrate de que esta dirección sea la que obtuviste en el deploy)
      BLOCKCHAIN_RPC_URL: "http://host.docker.internal:8545"
      CONTRACT_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3" 
      WALLET_PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      INVOICE_ENCRYPTION_KEY: "12345678901234567890123456789012"
    
    restart: unless-stopped

  # --- 3. FRONTEND (REACT) ---
  frontend:
    build: ./Frontend/core
    container_name: restaurant_frontend_container
    ports:
      - "3000:80" # O el puerto que uses (5173 para Vite, 3000 para React standard)
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
