version: '3.8'

services:
  # --- 1. BASE DE DATOS ---
  postgres:
    build: ./Backend/baseDatos
    container_name: restaurant_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # --- 2. BACKEND (API GO) ---
  backend:
    build: ./Backend/api
    container_name: restaurant_app_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    
    # Nota: Ya no necesitamos "extra_hosts" porque vamos a internet (Alchemy),
    # no a tu m√°quina local.
    
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BLOCKCHAIN_RPC_URL: ${BLOCKCHAIN_RPC_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      WALLET_PRIVATE_KEY: ${WALLET_PRIVATE_KEY}
      INVOICE_ENCRYPTION_KEY: ${INVOICE_ENCRYPTION_KEY}
    restart: unless-stopped

  # --- 3. FRONTEND (REACT) ---
  frontend:
    build: 
      context: ./Frontend/core
      # Inyectamos la IP al momento de construir la imagen
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: restaurant_frontend_container
    ports:
      - "3000:80" 
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
